# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skr386XDd8s-LzM5KSH2T7dGA_to-xfe
"""

#Aluno: Kayki Hiroyuki Lira Matos Hangui
#Questão 5, ferramentas tecnológicas utilizadas no projeto final de Introdução à Programação

#a) Qual foi o framework ou ferramenta tecnológica utilizada no seu projeto final?
#Explique brevemente para que ele serve e por que você (ou seu grupo) escolheu usá-lo no desenvolvimento.

Nós escolhemos usar a ferramenta tecnológica N8N, ele é uma ferramenta para conectar Apis, banco de dados, serviços web e automações, estamos usando para interligar uma API de
raspagem de dados com outras ferramentas com o objetivo de criar roteiros automatizados para a produção de conteúdos no aplicativo TikTok.

#b) Descreva uma funcionalidade concreta do seu projeto que foi construída usando esse framework.
#Explique com clareza o que essa funcionalidade faz, como ela foi implementada e quais recursos específicos do framework foram aplicados para torná-la possível.

Nós estamos conseguindo criar roteiros automatizados para o TikTok de forma específica para cada nicho (entrenimento, ensino, culinária, etc) por meio de uma API que raspa os
dados dos vídeos dessa plataforma de acordo com as hasthags inseridas pelo usuário, hasthags essas que devem ser as com maior relação aos vídeos de seu nicho, e em associação
com essas informações uma IA (estamos usando o groq) cria os roteiros para a produção de conteúdo.

#c) Indique alguma funcionalidade ou recurso que você pesquisou, mas ainda não conseguiu implementar.

Nós ainda não conseguimos, mas pretendemos, futuramente, usar uma IA que com todas essas informações e o roteiro já pronto, crie vídeos de animação com avatares personalizados
por nós, e que ficarão à escolha do usuário, de forma automatizada.