# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skr386XDd8s-LzM5KSH2T7dGA_to-xfe
"""



#Aluno: Kayki Hiroyuki Lira Matos Hangui
#Questão 1, estimar o consumo mensal de energia de aparelhos residenciais

#a)

def calcular_consumo_mensal(potencia_kw, horas_por_dia):
 return potencia_kw * horas_por_dia * 30

try:
 potencia = float(input("informe a potencia do aparelho em kW:(ex:1.2, 1.8)"))
 horas_por_dia = float(input("informe o tempo medio de uso diário em horas:(ex:4, 7) "))

 #Solicitei a potência do aparelho e o tempo médio de uso por dia, com o input() e depois convertendo para float

#b)

 if potencia <= 0 or horas_por_dia <=0:
  print("Valores devem ser positivos(acima de 0).")
 elif potencia > 100 or horas_por_dia > 24:
  print("Valores muito altos. Preste atenção os dados")

#Verifiquei se os valores eram positivos e dentro de uma faixa de normalidade, do contrário o programa avisava com uma mensagem

#c)

 else:
  consumo= calcular_consumo_mensal(potencia, horas_por_dia)
  print(f"Consumo mensal estimado(esperado): {consumo:.2f} KWh")

#Criei uma função que recebe a potência e o tempo de uso diário e calculo com a forma da questão

#d)

except ValueError:
  print("Entrada inválida.Preste atenção, coloque apenas números válidos")

#Demonstrei a resposta com duas casas decimais e usei o except para tratar erros de digitação e com isso evitar falhas