# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skr386XDd8s-LzM5KSH2T7dGA_to-xfe
"""

#Aluno: Kayki Hiroyuki Lira Matos Hangui
#Questão 6,  dashboard criptomoedas
#Número da matrícula 202504017

#a)

import requests
import time
from IPython.display import clear_output

#Aqui eu importo as bibliotecas necessárias: requests pra buscar os dados da internet (no caso, da API da CoinGecko), time pra dar umas pausas entre as atualizações
# clear_output pra limpar a tela do Colab e deixar tudo organizadinho, sem repetir texto à toa


#b)

def buscar_dados(moeda="bitcoin"):
    url = f"https://api.coingecko.com/api/v3/simple/price?ids={moeda}&vs_currencies=usd,brl"
    try:
        resposta = requests.get(url)
        resposta.raise_for_status()
        return resposta.json()[moeda]
    except:
        return None

#Aqui eu defino uma função chamada buscar_dados() que vai até a API da CoinGecko e busca o preço atualizado da criptomoeda que o usuário escolher, tanto em dólar quanto em real,
#se a API der erro, a função devolve None (vazio), e o código trata isso depois.


#c)

def mostrar_menu():
    print("🐍 Bem-vindo ao Mini Dashboard de Criptomoedas 💸")
    print("Escolha a moeda que cê quer acompanhar:")
    print("1 - Bitcoin")
    print("2 - Ethereum")
    print("3 - Dogecoin")
    print("0 - Sair do sistema")

#Função só pra mostrar o menu pro usuário poder escolher qual moeda ele quer espiar.


#d)

def rodar_dashboard():
    opcoes = {
        "1": "bitcoin",
        "2": "ethereum",
        "3": "dogecoin"
    }

    while True:
        clear_output(wait=True)
        mostrar_menu()
        escolha = input("Digite o número da moeda: ")

        if escolha == "0":
            print("Falô, brigadão! Volta sempre que quiser dar uma olhada no mercado 👋")
            break

        moeda = opcoes.get(escolha)
        if not moeda:
            print("Uai, essa opção aí não existe não, sô. Tenta de novo...")
            time.sleep(2)
            continue

        while True:
            clear_output(wait=True)
            print(f"⏳ Atualizando valores de {moeda.capitalize()} em tempo real...\n")
            dados = buscar_dados(moeda)

            if dados:
                print(f"📈 {moeda.upper()}")
                print(f"💵 Dólar (USD): ${dados['usd']:.2f}")
                print(f"🇧🇷 Real (BRL): R${dados['brl']:.2f}")
            else:
                print("Eita! Não deu pra buscar os dados agora. A internet deve ter dado uma rateada.")

            print("\n🔁 Atualizando de novo em 10 segundos...")
            print("🔙 Se quiser voltar pro menu, é só parar a célula (botão ■ ali em cima).")
            time.sleep(10)

#Essa função é o coração do sistema:
#Primeiro mostra o menu pro caboclo escolher a moeda
# Depois entra num laço que fica buscando os preços atualizados e mostrando bonitinho
# A cada 10 segundos ele limpa a tela e busca de novo
#Se quiser parar, é só parar a célula (igual parar uma música)

#e)
rodar_dashboard()

#Aqui é onde o sistema realmente começa a rodar, chamei a função rodar_dashboard() pra começar o painel de controle, tudo que o usuário precisa fazer é apertar ▶️ no Colab e
#interagir com o menu.